version: '3.8'

services:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ../certbot-data/conf:/etc/letsencrypt
      - ../certbot-data/www:/var/www/certbot
      - ../certbot-data/logs:/var/log/letsencrypt
    networks:
      - ssairen-net

networks:
  ssairen-net:
    external: true
